apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  annotations:
    gethomepage.dev/href: "https://prometheus.homelab.eeternalsadness.dev"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Prometheus
    gethomepage.dev/group: Platform
    gethomepage.dev/app: prometheus # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/icon: prometheus.png # icons from https://github.com/homarr-labs/dashboard-icons/tree/main/png
    gethomepage.dev/name: Prometheus
    # health check
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=prometheus"
    # external dns
    external-dns.alpha.kubernetes.io/target: "traefik-lb.homelab.eeternalsadness.dev"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`prometheus.homelab.eeternalsadness.dev`)
      priority: 10
      services:
        - name: kube-prometheus-kube-prome-prometheus
          port: 9090
  tls:
    secretName: prometheus-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  annotations:
    gethomepage.dev/href: "https://grafana.homelab.eeternalsadness.dev"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Grafana
    gethomepage.dev/group: Platform
    gethomepage.dev/app: grafana # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/icon: grafana.png # icons from https://github.com/homarr-labs/dashboard-icons/tree/main/png
    gethomepage.dev/name: Grafana
    # health check
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=grafana"
    # external dns
    external-dns.alpha.kubernetes.io/target: "traefik-lb.homelab.eeternalsadness.dev"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`grafana.homelab.eeternalsadness.dev`)
      priority: 10
      services:
        - name: kube-prometheus-grafana
          port: 80
  tls:
    secretName: grafana-tls
