apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kubernetes-mcp-server
  annotations:
    # external dns
    external-dns.alpha.kubernetes.io/target: "traefik-lb.homelab.eeternalsadness.dev"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`mcp.homelab.eeternalsadness.dev`) && (Path(`/kubernetes`) || PathPrefix(`/kubernetes/`))
      middlewares:
        - name: kubernetes-mcp-server-replacepathregex
      priority: 10
      services:
        - name: kubernetes-mcp-server
          port: 8080
  tls:
    secretName: mcp-tls
