apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  project: default
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  sources:
    - chart: kube-prometheus-stack
      repoURL: "https://prometheus-community.github.io/helm-charts"
      targetRevision: 70.3.0
      helm:
        valueFiles:
          - $values/2-infra/dev/kube-prometheus/values/values-grafana.yaml
          - $values/2-infra/dev/kube-prometheus/values/values-prometheus.yaml
          - $values/2-infra/dev/kube-prometheus/values/values.yaml
    # values files reference
    - repoURL: "https://github.com/eeternalsadness/homelab.git"
      targetRevision: main
      ref: values
    # resources
    - repoURL: "https://github.com/eeternalsadness/homelab.git"
      targetRevision: main
      path: 2-infra/dev/kube-prometheus/resources
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
