prometheus:
  enabled: true

  prometheusSpec:
    retention: 14d
    resources: {}

  ingress:
    enabled: false

    # data persistence
    # storageSpec:
    #   volumeClaimTemplate:
    #     spec:
    #       storageClassName: default
    #       accessModes: ["ReadWriteOnce"]
    #       resources:
    #         requests:
    #           storage: 10Gi
