grafana:
  enabled: true

  defaultDashboardsEnabled: true
  defaultDashboardsTimezone: Asia/Singapore

  # configure admin credentials from existing secret
  admin:
    existingSecret: "grafana-admin"
    userKey: username
    passwordKey: password

  ingress:
    enabled: true
    annotations:
      gethomepage.dev/href: "https://grafana.homelab.eeternalsadness.dev"
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: Grafana
      gethomepage.dev/group: Platform
      gethomepage.dev/app: grafana # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
      gethomepage.dev/icon: grafana.png # icons from https://github.com/homarr-labs/dashboard-icons/tree/main/png
      gethomepage.dev/name: Grafana
      # health check
      gethomepage.dev/pod-selector: "app.kubernetes.io/name=grafana"
    hosts:
      - grafana.homelab.eeternalsadness.dev
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.homelab.eeternalsadness.dev

  grafana.ini:
    server:
      # NOTE: used for redirects (e.g. OIDC)
      root_url: https://grafana.homelab.eeternalsadness.dev

  resources: {}

  persistence:
    enabled: false
