# https://argo-cd.readthedocs.io/en/latest/operator-manual/ingress/#traefik-v30
# the config options are very similar to HAProxy
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    gethomepage.dev/href: "https://argocd.homelab.eeternalsadness.dev"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: ArgoCD
    gethomepage.dev/group: Platform
    gethomepage.dev/app: argocd-server # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/icon: argo-cd.png # icons from https://github.com/homarr-labs/dashboard-icons/tree/main/png
    gethomepage.dev/name: ArgoCD
    # health check
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=argocd-server"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.homelab.eeternalsadness.dev`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.homelab.eeternalsadness.dev`) && Header(`Content-Type`, `application/grpc`)
      priority: 11 # higher number = higher priority
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: argocd-tls
